INSERT INTO processos (processo_id, cnjnumber, partes, tribunalorigem, data) VALUES (1, '0000000-00.0000.0.00.0000', 'Autor: Rogerio Abreu / Reu: Carlos Henrique', 'federal court','24/02/2022');
INSERT INTO processos (processo_id, cnjnumber, partes, tribunalorigem, data) VALUES (2, '0000001-00.0000.0.00.0000', 'Autor: Pedro Rodrigues / Reu: Helio Costa', 'supreme court','27/02/2022');
INSERT INTO processos (processo_id, cnjnumber, partes, tribunalorigem, data) VALUES (3, '0000002-00.0000.0.00.0000', 'Autor: Fernando Souza / Reu: Jonas Souza', 'court of law','20/02/2022');
INSERT INTO processos (processo_id, cnjnumber, partes, tribunalorigem, data) VALUES (4, '0000003-00.0000.0.00.0000', 'Autor: Sergio Felipe / Reu: Joao Henrique', 'federal court','23/02/2022');
INSERT INTO processos (processo_id, cnjnumber, partes, tribunalorigem, data) VALUES (5, '0000004-00.0000.0.00.0000', 'Autor: Gustavo Costa / Reu: Claudia Moreno', 'federal court','21/02/2022');

INSERT INTO movimentacoes (processo_id_Fk, data, description) VALUES (1, '23/02/2022', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO movimentacoes (processo_id_Fk, data, description) VALUES (2, '23/02/2022', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO movimentacoes (processo_id_Fk, data, description) VALUES (3, '23/02/2022', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO movimentacoes (processo_id_Fk, data, description) VALUES (4, '23/02/2022', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO movimentacoes (processo_id_Fk, data, description) VALUES (5, '23/02/2022', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');

